from pathlib import Path
import sqlite3

import pandas as pd

# Project paths

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "data" / "raw"
DATA_DIR = BASE_DIR / "data"
PROCESSED_DIR = DATA_DIR / "processed"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
DATA_DIR.mkdir(parents=True, exist_ok=True)

DB_PATH = DATA_DIR / "financial_report.db"


# Utility functions

def read_csv_safely(filename: str) -> pd.DataFrame:
    """
    Read CSV from data/raw folder.
    If file is missing or empty, return an empty DataFrame.
    """
    path = OUTPUT_DIR / filename

    if not path.exists():
        print(f"File not found: {path}")
        return pd.DataFrame()

    try:
        df = pd.read_csv(path)
        print(f"Loaded {filename}: {df.shape}")
        return df
    except pd.errors.EmptyDataError:
        print(f"Empty file: {filename}")
        return pd.DataFrame()
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return pd.DataFrame()


def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    General cleaning:
    - remove fully empty rows/columns
    - remove duplicate columns
    - strip column names
    """
    if df.empty:
        return df

    df = df.copy()

    df.columns = [str(col).strip() for col in df.columns]

    df = df.dropna(axis=0, how="all")
    df = df.dropna(axis=1, how="all")
    df = df.loc[:, ~df.columns.duplicated()]

    return df


def select_existing_columns(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """
    Select only columns that exist in the DataFrame.
    This avoids KeyError if FMP response columns differ.
    """
    if df.empty:
        return df

    existing_columns = [col for col in columns if col in df.columns]

    if not existing_columns:
        return df

    return df[existing_columns].copy()


def convert_numeric_columns(df: pd.DataFrame, exclude_columns: list[str] | None = None) -> pd.DataFrame:
    """
    Try converting suitable columns to numeric.

    Uses errors='coerce' only when the column appears numeric enough.
    This avoids pandas errors and avoids converting text columns into NaN.
    """
    if df.empty:
        return df

    if exclude_columns is None:
        exclude_columns = []

    df = df.copy()

    for col in df.columns:
        if col in exclude_columns:
            continue

        original_series = df[col]
        converted_series = pd.to_numeric(original_series, errors="coerce")

        if converted_series.notna().sum() > 0:
            df[col] = converted_series

    return df


def save_processed_csv(df: pd.DataFrame, filename: str):
    """
    Save processed DataFrame to data/processed.
    """
    path = PROCESSED_DIR / filename
    df.to_csv(path, index=False)
    print(f"Saved processed CSV: {path}")


def prepare_for_sqlite(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert unsupported pandas/numpy objects into SQLite-friendly values.
    Especially handles Timestamp values in normal columns and object columns.
    """
    if df.empty:
        return df

    df = df.copy()

    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = df[col].astype(str)

        elif df[col].dtype == "object":
            df[col] = df[col].apply(
                lambda x: x.isoformat() if isinstance(x, pd.Timestamp) else x
            )

    return df


def save_to_sqlite(tables: dict[str, pd.DataFrame]):
    """
    Save processed DataFrames into SQLite database.
    Converts Timestamp values before saving.
    """
    conn = sqlite3.connect(DB_PATH)

    for table_name, df in tables.items():
        sqlite_ready_df = prepare_for_sqlite(df)

        sqlite_ready_df.to_sql(
            table_name,
            conn,
            if_exists="replace",
            index=False
        )

        print(f"Saved table '{table_name}' to SQLite. Shape: {sqlite_ready_df.shape}")

    conn.close()
    print(f"SQLite database saved at: {DB_PATH}")


# Load raw CSV files generated by fetch_data.py

profile_df = read_csv_safely("company_profile.csv")
quote_df = read_csv_safely("stock_quote.csv")
income_df = read_csv_safely("income_statement.csv")
balance_df = read_csv_safely("balance_sheet.csv")
cashflow_df = read_csv_safely("cash_flow.csv")
economic_df = read_csv_safely("economic_indicators.csv")


# Clean raw DataFrames

profile_df = clean_dataframe(profile_df)
quote_df = clean_dataframe(quote_df)
income_df = clean_dataframe(income_df)
balance_df = clean_dataframe(balance_df)
cashflow_df = clean_dataframe(cashflow_df)
economic_df = clean_dataframe(economic_df)


# Select useful columns

profile_columns = [
    "symbol",
    "companyName",
    "price",
    "marketCap",
    "beta",
    "lastDividend",
    "range",
    "change",
    "changePercentage",
    "volume",
    "averageVolume",
    "currency",
    "cik",
    "isin",
    "cusip",
    "exchangeFullName",
    "exchange",
    "industry",
    "website",
    "description",
    "ceo",
    "sector",
    "country",
    "fullTimeEmployees",
    "phone",
    "address",
    "city",
    "state",
    "zip",
    "image",
    "ipoDate",
    "defaultImage",
    "isEtf",
    "isActivelyTrading",
    "isAdr",
    "isFund"
]

quote_columns = [
    "symbol",
    "name",
    "price",
    "changesPercentage",
    "change",
    "dayLow",
    "dayHigh",
    "yearHigh",
    "yearLow",
    "marketCap",
    "priceAvg50",
    "priceAvg200",
    "exchange",
    "volume",
    "avgVolume",
    "open",
    "previousClose",
    "eps",
    "pe",
    "earningsAnnouncement",
    "sharesOutstanding",
    "timestamp"
]

income_columns = [
    "date",
    "symbol",
    "reportedCurrency",
    "period",
    "revenue",
    "costOfRevenue",
    "grossProfit",
    "grossProfitRatio",
    "researchAndDevelopmentExpenses",
    "generalAndAdministrativeExpenses",
    "sellingAndMarketingExpenses",
    "sellingGeneralAndAdministrativeExpenses",
    "operatingExpenses",
    "operatingIncome",
    "operatingIncomeRatio",
    "ebitda",
    "ebitdaratio",
    "netIncome",
    "netIncomeRatio",
    "eps",
    "epsdiluted",
    "weightedAverageShsOut",
    "weightedAverageShsOutDil"
]

balance_columns = [
    "date",
    "symbol",
    "reportedCurrency",
    "period",
    "cashAndCashEquivalents",
    "shortTermInvestments",
    "cashAndShortTermInvestments",
    "netReceivables",
    "inventory",
    "totalCurrentAssets",
    "propertyPlantEquipmentNet",
    "goodwill",
    "intangibleAssets",
    "totalAssets",
    "accountPayables",
    "shortTermDebt",
    # taxPayables intentionally removed from balance_sheet_processed
    "deferredRevenue",
    "totalCurrentLiabilities",
    "longTermDebt",
    "totalDebt",
    "totalLiabilities",
    "totalStockholdersEquity",
    "totalEquity",
    "totalLiabilitiesAndStockholdersEquity"
]

cashflow_columns = [
    "date",
    "symbol",
    "reportedCurrency",
    "period",
    "netIncome",
    "depreciationAndAmortization",
    "deferredIncomeTax",
    "stockBasedCompensation",
    "changeInWorkingCapital",
    "accountsReceivables",
    "inventory",
    "accountsPayables",
    "otherWorkingCapital",
    "operatingCashFlow",
    "capitalExpenditure",
    "freeCashFlow",
    "netCashProvidedByOperatingActivities",
    "netCashUsedForInvestingActivites",
    "netCashUsedProvidedByFinancingActivities"
]

economic_columns = [
    "date",
    "value",
    "indicator",
    "indicators"
]


profile_processed = select_existing_columns(profile_df, profile_columns)
quote_processed = select_existing_columns(quote_df, quote_columns)
income_processed = select_existing_columns(income_df, income_columns)
balance_processed = select_existing_columns(balance_df, balance_columns)
cashflow_processed = select_existing_columns(cashflow_df, cashflow_columns)
economic_processed = select_existing_columns(economic_df, economic_columns)


# Extra safety: drop taxPayable/taxPayables if present in balance sheet

if not balance_processed.empty:
    balance_processed = balance_processed.drop(
        columns=["taxPayable", "taxPayables"],
        errors="ignore"
    )


# Replace GDP with GDP_BillionUSD in economic indicators

if not economic_processed.empty:
    for indicator_col in ["indicator", "indicators"]:
        if indicator_col in economic_processed.columns:
            economic_processed[indicator_col] = economic_processed[indicator_col].replace(
                "GDP",
                "GDP_BillionUSD"
            )


# Convert date and numeric columns

date_tables = [
    income_processed,
    balance_processed,
    cashflow_processed,
    economic_processed
]

for df in date_tables:
    if not df.empty and "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")


profile_processed = convert_numeric_columns(
    profile_processed,
    exclude_columns=[
        "symbol", "companyName", "currency", "cik", "isin", "cusip",
        "exchangeFullName", "exchange", "industry", "website",
        "description", "ceo", "sector", "country", "phone",
        "address", "city", "state", "zip", "image", "ipoDate"
    ]
)

quote_processed = convert_numeric_columns(
    quote_processed,
    exclude_columns=["symbol", "name", "exchange", "earningsAnnouncement"]
)

income_processed = convert_numeric_columns(
    income_processed,
    exclude_columns=["date", "symbol", "reportedCurrency", "period"]
)

balance_processed = convert_numeric_columns(
    balance_processed,
    exclude_columns=["date", "symbol", "reportedCurrency", "period"]
)

cashflow_processed = convert_numeric_columns(
    cashflow_processed,
    exclude_columns=["date", "symbol", "reportedCurrency", "period"]
)

economic_processed = convert_numeric_columns(
    economic_processed,
    exclude_columns=["date", "indicator", "indicators"]
)


# Sort financial statements by date descending

for df_name, df in {
    "income_processed": income_processed,
    "balance_processed": balance_processed,
    "cashflow_processed": cashflow_processed,
    "economic_processed": economic_processed
}.items():
    if not df.empty and "date" in df.columns:
        df.sort_values("date", ascending=False, inplace=True)
        print(f"Sorted {df_name} by date.")


# Create computed metrics

computed_metrics = {}

if not income_processed.empty:
    income_sorted = income_processed.sort_values("date", ascending=False).reset_index(drop=True)

    if len(income_sorted) >= 2:
        latest = income_sorted.iloc[0]
        previous = income_sorted.iloc[1]

        latest_revenue = latest.get("revenue")
        previous_revenue = previous.get("revenue")

        latest_net_income = latest.get("netIncome")
        previous_net_income = previous.get("netIncome")

        if pd.notna(latest_revenue) and pd.notna(previous_revenue) and previous_revenue != 0:
            computed_metrics["revenue_growth_pct"] = round(
                ((latest_revenue - previous_revenue) / previous_revenue) * 100,
                2
            )

        if pd.notna(latest_net_income) and pd.notna(previous_net_income) and previous_net_income != 0:
            computed_metrics["net_income_growth_pct"] = round(
                ((latest_net_income - previous_net_income) / previous_net_income) * 100,
                2
            )

        # Removed:
        # computed_metrics["latest_income_statement_date"]
        # computed_metrics["previous_income_statement_date"]


if not balance_processed.empty:
    balance_sorted = balance_processed.sort_values("date", ascending=False).reset_index(drop=True)
    latest_balance = balance_sorted.iloc[0]

    total_assets = latest_balance.get("totalAssets")
    total_liabilities = latest_balance.get("totalLiabilities")
    total_equity = latest_balance.get("totalStockholdersEquity")
    total_debt = latest_balance.get("totalDebt")
    cash = latest_balance.get("cashAndCashEquivalents")

    if pd.notna(total_liabilities) and pd.notna(total_equity) and total_equity != 0:
        computed_metrics["debt_to_equity_proxy"] = round(total_liabilities / total_equity, 2)

    if pd.notna(total_debt) and pd.notna(cash):
        computed_metrics["net_debt"] = total_debt - cash

    if pd.notna(total_assets) and pd.notna(total_liabilities):
        computed_metrics["asset_liability_gap"] = total_assets - total_liabilities

    computed_metrics["latest_balance_sheet_date"] = latest_balance.get("date")


if not cashflow_processed.empty:
    cashflow_sorted = cashflow_processed.sort_values("date", ascending=False).reset_index(drop=True)
    latest_cashflow = cashflow_sorted.iloc[0]

    operating_cash_flow = latest_cashflow.get("operatingCashFlow")
    free_cash_flow = latest_cashflow.get("freeCashFlow")
    capital_expenditure = latest_cashflow.get("capitalExpenditure")

    computed_metrics["latest_operating_cash_flow"] = operating_cash_flow
    computed_metrics["latest_free_cash_flow"] = free_cash_flow
    computed_metrics["latest_capital_expenditure"] = capital_expenditure

    # Removed:
    # computed_metrics["latest_cash_flow_date"]


computed_metrics_df = pd.DataFrame(
    [
        {"metric": key, "value": value}
        for key, value in computed_metrics.items()
    ]
)

print("\nComputed Metrics:")
print(computed_metrics_df)


# Save processed CSV files

save_processed_csv(profile_processed, "company_profile_processed.csv")
save_processed_csv(quote_processed, "stock_quote_processed.csv")
save_processed_csv(income_processed, "income_statement_processed.csv")
save_processed_csv(balance_processed, "balance_sheet_processed.csv")
save_processed_csv(cashflow_processed, "cash_flow_processed.csv")
save_processed_csv(economic_processed, "economic_indicators_processed.csv")
save_processed_csv(computed_metrics_df, "computed_metrics.csv")


tables = {
    "company_profile": profile_processed,
    "stock_quote": quote_processed,
    "income_statement": income_processed,
    "balance_sheet": balance_processed,
    "cash_flow": cashflow_processed,
    "economic_indicators": economic_processed,
    "computed_metrics": computed_metrics_df
}

save_to_sqlite(tables)